// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Represents a request message for the chat service.
#
# + sessionId - A unique identifier for the chat session.
# + message - The content of the chat message sent by the user.
public type ChatReqMessage record {|
    string sessionId;
    string message;
|};

# Represents a response message from the chat service.
#
# + message - The response message generated by the chat service.
public type ChatRespMessage record {|
    string message;
|};

# Represents a structured decision on the tool call(s) a paused run is awaiting approval for.
# Sent to a chat service's `decision` resource to resume the run for `sessionId`.
#
# + sessionId - The session whose paused run these decisions apply to
# + decisions - The human's decisions, keyed by `ApprovalRequest.id`
public type DecisionMessage readonly & record {|
    string sessionId;
    map<HumanResponse> decisions;
|};

# Represents the configuration for a chat client.
public type ChatClientConfiguration record {|
    *http:ClientConfiguration;
|};

# Defines a chat service interface that handles incoming chat messages.
public type ChatService distinct service object {
    *http:Service;
    resource function post chat(@http:Payload ChatReqMessage request) returns ChatRespMessage|error;
};

type ExecutionTrace record {|
    (ExecutionResult|ExecutionError|Error)[] steps;
    string answer?;
    Iteration[] iterations;
    FunctionCall[] toolCalls;
    ApprovalRequiredError? pendingApproval = ();
    # A terminal error that must be surfaced to the caller instead of any pause/answer - e.g. the
    # pending-approval checkpoint failed to persist, so the run cannot be reported as a resumable
    # pause. Takes precedence over `pendingApproval` when building the outcome.
    Error? fatalError = ();
    boolean maxIterationsExceeded = false;
|};

# Configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Configuration"}
public type ConnectionConfig record {|

    # The HTTP version understood by the client
    @display {label: "HTTP Version"}
    http:HttpVersion httpVersion = http:HTTP_2_0;

    # Configurations related to HTTP/1.x protocol
    @display {label: "HTTP1 Settings"}
    http:ClientHttp1Settings http1Settings = {};

    # Configurations related to HTTP/2 protocol
    @display {label: "HTTP2 Settings"}
    http:ClientHttp2Settings http2Settings = {};

    # The maximum time to wait (in seconds) for a response before closing the connection
    @display {label: "Timeout"}
    decimal timeout = 60;

    # The choice of setting `forwarded`/`x-forwarded` header
    @display {label: "Forwarded"}
    string forwarded = "disable";

    # Configurations associated with request pooling
    @display {label: "Pool Configuration"}
    http:PoolConfiguration poolConfig?;

    # HTTP caching related configurations
    @display {label: "Cache Configuration"}
    http:CacheConfig cache = {};

    # Specifies the way of handling compression (`accept-encoding`) header
    @display {label: "Compression"}
    http:Compression compression = http:COMPRESSION_AUTO;

    # Configurations associated with the behaviour of the Circuit Breaker
    @display {label: "Circuit Breaker Configuration"}
    http:CircuitBreakerConfig circuitBreaker?;

    # Configurations associated with retrying
    @display {label: "Retry Configuration"}
    http:RetryConfig retryConfig?;

    # Configurations associated with inbound response size limits
    @display {label: "Response Limit Configuration"}
    http:ResponseLimitConfigs responseLimits = {};

    # SSL/TLS-related options
    @display {label: "Secure Socket Configuration"}
    http:ClientSecureSocket secureSocket?;

    # Proxy server related options
    @display {label: "Proxy Configuration"}
    http:ProxyConfig proxy?;

    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    @display {label: "Payload Validation"}
    boolean validation = true;
|};

# Represent the automatic chunker configuration in the `VectorKnowledgeBase`.
# This chunker will be chosen automatically based on the document type.
public const AUTO = "AUTO";

# Represents the disabled chunker configuration in the `VectorKnowledgeBase`.
# This chunker will not perform any chunking and will treat the entire document as a single chunk.
public const DISABLE = "DISABLE";

# Represents the configuration for the `ModelProvider.generate()` method.
public type GeneratorConfig record {|
    # Configuration for retrying on response parsing failures
    @display {label: "Retry Configuration"}
    RetryConfig retryConfig?;
|};

# Represents retry configuration on response parsing failures.
public type RetryConfig record {|
    # Number of retry attempts
    @display {label: "Retry Count"}
    int count = 0;

    # Retry interval in seconds
    @display {label: "Retry Interval"}
    decimal interval?;
|};

# Defines the strategies for loading tool schemas into an Agent.
public enum ToolLoadingStrategy {
    # Loads all available tools without any filtering.
    NO_FILTER,

     # Uses a selective, double-dispatch strategy.
     #
     # Instead of sending all tool schemas directly to the LLM, only a list of tool names
     # and descriptions is sent initially. The LLM then selects the tools needed to handle
     # the user’s query. Once the required tools are identified, their corresponding schemas
     # are loaded and sent to the LLM to obtain the necessary parameters for execution.
    LLM_FILTER
}

# Configuration options for the Streamable HTTP client transport.
public type StreamableHttpClientTransportConfig record {|
    # HTTP protocol version supported by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # HTTP/1.x specific settings
    http:ClientHttp1Settings http1Settings = {};
    # HTTP/2 specific settings
    http:ClientHttp2Settings http2Settings = {};
    # Maximum time(in seconds) to wait for a response before the request times out
    decimal timeout = 30;
    # The choice of setting `Forwarded`/`X-Forwarded-For` header, when acting as a proxy
    string forwarded = "disable";
    # HTTP redirect handling configurations (with 3xx status codes)
    http:FollowRedirects? followRedirects = ();
    # Configurations associated with the request connection pool
    http:PoolConfiguration? poolConfig = ();
    # HTTP response caching related configurations
    http:CacheConfig cache = {};
    # Enable request/response compression (using `accept-encoding` header)
    http:Compression compression = http:COMPRESSION_AUTO;
    # Client authentication options (Basic, Bearer token, OAuth, etc.)
    # Circuit breaker configurations to prevent cascading failures
    http:CircuitBreakerConfig? circuitBreaker = ();
    # Automatic retry settings for failed requests
    http:RetryConfig? retryConfig = ();
    # Cookie handling settings for session management
    http:CookieConfig? cookieConfig = ();
    # Configurations related to client authentication
    http:ClientAuthConfig|AgentIdAuthConfig? auth = ();
    # Limits for response size and headers (to prevent memory issues)
    http:ResponseLimitConfigs responseLimits = {};
    # Proxy server settings if requests need to go through a proxy
    http:ProxyConfig? proxy = ();
    # Enable automatic payload validation for request/response data against constraints
    boolean validation = true;
    # Low-level socket settings (timeouts, buffer sizes, etc.)
    http:ClientSocketConfig socketConfig = {};
    # Enable relaxed data binding on the client side.
    # When enabled:
    # - `null` values in JSON are allowed to be mapped to optional fields
    # - missing fields in JSON are allowed to be mapped as `null` values
    boolean laxDataBinding = false;
    # SSL/TLS-related options
    http:ClientSecureSocket? secureSocket = ();
    # Optional session identifier for continued interactions
    string sessionId?;
|};

# Represents the OAuth 2.0 client configuration required to interact
# with an external Authorization Server and validate issued access tokens.
@display {label: "OAuth Client Configuration"}
public type AgentIdAuthConfig record {|

    # The base URL of the Authorization Server used to resolve
    # OAuth 2.0 endpoints such as authorization, token, and introspection.
    @display {label: "Authorization Server Base URL"}
    string baseAuthUrl;

    # The OAuth 2.0 client identifier issued to this client application.
    @display {label: "Client ID"}
    string clientId;

    # The OAuth 2.0 client secret issued to this client application.
    @display {label: "Client Secret"}
    string clientSecret?;

    # The redirect URI registered for the OAuth client and used
    # in the Authorization Code flow.
    @display {label: "Redirect URI"}
    string redirectUri;

    # Scopes required to invoke this tool
    @display {label: "Required Scopes"}
    string|string[] scopes?;

    # Indicates whether PKCE (Proof Key for Code Exchange) is enabled
    # for the Authorization Code flow.
    @display {label: "Enable PKCE"}
    boolean isPkceEnabled = false;
    
    # SSL/TLS-related options
    http:ClientSecureSocket? secureSocket = ();
|};

# Represents the OAuth scopes required for invoking a tool.
public type Scopes record {|
    # The required OAuth scope or list of scopes.
    string|string[] scopes?;
|};
